@hostname = 127.0.0.1 
@port = 5101 
@host = https://{{hostname}}:{{port}} 
@contentType = application/json

###
GET {{host}}/api/users

###
POST {{host}}/api/users
Content-Type: {{contentType}}

{
    "FirstName": "Tyler",
    "LastName": "Jones",
    "Id": 42
}

###
POST {{host}}/api/users
Content-Type: {{contentType}}

{
    "FirstName": "Riah",
    "LastName": "Franko",
    "Id": 9
}

###
POST {{host}}/api/users
Content-Type: {{contentType}}

{
    "FirstName": "Obediah",
    "LastName": "Slytherin",
    "Id": 33
}

###
GET {{host}}/api/users/1

###
DELETE {{host}}/api/users/0

###
DELETE {{host}}/api/users/5
###
PUT {{host}}/api/users/1
Content-Type: {{contentType}}

{
    "FirstName": "Mia",
    "LastName": "Hunt",
    "Id" : 13
}

###
PUT {{host}}/api/users/2
Content-Type: {{contentType}}

{
    "FirstName": "Updated",
    "LastName": "Person",
    "Id" : 35
}

###
PUT {{host}}/api/users/3
Content-Type: {{contentType}}

{
    "FirstName": "Updated",
    "LastName": "Person",
    "Id" : 35
}