# Docs for the Azure Web Apps Deploy action: https://go.microsoft.com/fwlink/?linkid=2134798
# More GitHub Actions for Azure: https://go.microsoft.com/fwlink/?linkid=2135048

name: Deployment

on:
  push:
    branches: [ Assignment* ]
  pull_request:
    branches: [ Assignment* ]

jobs:
  build:
    defaults:
      run:
        working-directory: ./SecretSanta/
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
 
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Get Directory
      run: pwd

    - name: npm install
      working-directory: ./SecretSanta/src/SecretSanta.Web/
      run: npm install
    - name: npm build
      working-directory: ./SecretSanta/src/SecretSanta.Web/
      run: npm run build:prod

    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore --configuration Release

    - name: dotnet publish (WEB)
      working-directory: ./SecretSanta/src/SecretSanta.Web/
      run: dotnet publish -c Release -o ${{env.DOTNET_ROOT}}/Web
      
    - name: dotnet publish (API)
      working-directory: ./SecretSanta/src/SecretSanta.Api/
      run: dotnet publish -c Release -o ${{env.DOTNET_ROOT}}/Api

    - name: Run Azure webapp deploy action using publish profile credentials (WEB)
      uses: azure/webapps-deploy@v2
      with:
        app-name: EWU-SecretSanta
        slot-name: Production
        publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_580CC115ABD5402AADBEEBBF6ED7966F }}
        package: ${{env.DOTNET_ROOT}}/Web
        
    - name: Run Azure webapp deploy action using publish profile credentials (API)
      uses: azure/webapps-deploy@v2
      with:
        app-name: EWU-SecretSanta-API
        slot-name: Production
        publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_0604EDABB4C5432CACA123FF1864DC6F }}
        package: ${{env.DOTNET_ROOT}}/Api

